# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 2.0-servicing

pool:
  vmImage: windows-latest

steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: 'src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj'
        includesymbols: true
        versioningScheme: 'off'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'push'
        packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
        nuGetFeedType: 'internal'
        publishVstsFeed: 'd85e9c14-95bd-4462-9c9e-94ff9ff63be4/c2902f4c-5a34-45a3-989d-66bcad68093e'
    
    
