name: .NET

on:
  push:
    branches: [2.0-servicing ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Restore dependencies
      run: dotnet restore src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
    - name: Build
      run: dotnet publish --framework netcoreapp3.1  src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
      # Artifact name
       name: Artifacts
       # A file, directory or wildcard pattern that describes what to upload
       path: /home/runner/work/SqlClient/SqlClient/artifacts/Project/bin/

    
